# Configuration for Prometheus
prometheus:
  enabled: true
  ingress:
    enabled: true # Enable Prometheus Ingress
    ingressClassName: nginx
    hosts:
      - prometheus-ui.com
    paths:
      - /
  prometheusSpec:
    serviceMonitorSelector:
      matchLabels:
        role: monitoring # Ensure this matches the ServiceMonitors in your setup

# Configuration for Grafana
grafana:
  enabled: true
  ingress:
    enabled: true # Enable Grafana Ingress
    ingressClassName: nginx
    hosts:
      - monitoring.com
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://my-loki.monitoring.svc.cluster.local:3100
      version: 1
