apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cadvisor
  namespace: cadvisor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      name: cadvisor
  endpoints:
    - port: http
