apiVersion: v1
kind: PersistentVolume
metadata:
  name: psql-pv-go
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /storage/db/go
    type: DirectoryOrCreate
